// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");
var TodoService = require("./src/TodoService.bs.js");
var TodoStateManager = require("./infrastructure/TodoStateManager.bs.js");
var TodoBrowserManager = require("./infrastructure/TodoBrowserManager.bs.js");

Belt_Result.getExn(TodoStateManager.TodoStateManager.writeResponsiblesState(TodoStateManager.TodoStateManager.initNominalData(undefined)));

var TodoServiceInBrowser = TodoService.TodoService(TodoBrowserManager.TodoBrowserManager, TodoStateManager.TodoStateManager);

Curry._1(TodoServiceInBrowser.rerenderClearForm, TodoServiceInBrowser.applyForm);

Curry._1(TodoServiceInBrowser.rerenderResponsibles, TodoServiceInBrowser.changeTask);

exports.TodoServiceInBrowser = TodoServiceInBrowser;
/*  Not a pure module */
