// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TodoTask = require("../src/TodoTask.bs.js");
var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Assert$RescriptMocha = require("rescript-mocha/lib/js/src/Assert.bs.js");

Mocha$RescriptMocha.describe("TodoTask")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.it("switchChecked")(undefined, undefined, undefined, (function (param) {
                var result = TodoTask.TodoTask.switchChecked({
                      id: "8asjd98as",
                      name: "kkkoliko",
                      isReady: false
                    });
                Assert$RescriptMocha.deep_equal(undefined, {
                      id: "8asjd98as",
                      name: "kkkoliko",
                      isReady: true
                    }, result);
              }));
      }));

/*  Not a pure module */
