// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";

function $$new(name) {
  return {
          id: Uuid.v4(),
          name: name,
          isReady: false
        };
}

function switchChecked(t) {
  return {
          id: t.id,
          name: t.name,
          isReady: !t.isReady
        };
}

export {
  $$new ,
  switchChecked ,
}
/* uuid Not a pure module */
