// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Result = require("rescript/lib/js/belt_Result.js");
var TodoStateManager = require("../infrastructure/TodoStateManager.bs.js");
var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Assert$RescriptMocha = require("rescript-mocha/lib/js/src/Assert.bs.js");

Mocha$RescriptMocha.describe("TodoStateManager")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.it("test 1")(undefined, undefined, undefined, (function (param) {
                var initResult = TodoStateManager.TodoStateManager.writeResponsiblesState(TodoStateManager.TodoStateManager.initNominalData(undefined));
                Assert$RescriptMocha.deep_equal(undefined, {
                      TAG: /* Ok */0,
                      _0: undefined
                    }, initResult);
                var readResult = Belt_Result.getExn(TodoStateManager.TodoStateManager.readResponsiblesState(undefined));
                Assert$RescriptMocha.deep_equal(undefined, readResult, TodoStateManager.TodoStateManager.initNominalData(undefined));
              }));
      }));

/*  Not a pure module */
