// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TodoResponsible = require("../src/TodoResponsible.bs.js");
var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Assert$RescriptMocha = require("rescript-mocha/lib/js/src/Assert.bs.js");

Mocha$RescriptMocha.describe("TodoResponsible")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.it("tryToSwitchChackedTask")(undefined, undefined, undefined, (function (param) {
                var given_tasks = [
                  {
                    id: "89sad98saa",
                    name: "nd9a8s",
                    isReady: true
                  },
                  {
                    id: "9a0smfa",
                    name: "lpo,o-[p[",
                    isReady: false
                  }
                ];
                var given = {
                  id: "hdsa7hd899as",
                  name: "Sam",
                  tasks: given_tasks
                };
                var result = TodoResponsible.TodoResponsible.tryToSwitchChackedTask(given, "9a0smfa");
                var nominal_tasks = [
                  {
                    id: "89sad98saa",
                    name: "nd9a8s",
                    isReady: true
                  },
                  {
                    id: "9a0smfa",
                    name: "lpo,o-[p[",
                    isReady: true
                  }
                ];
                var nominal = {
                  id: "hdsa7hd899as",
                  name: "Sam",
                  tasks: nominal_tasks
                };
                Assert$RescriptMocha.deep_equal(undefined, result, nominal);
              }));
      }));

/*  Not a pure module */
