// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function liftTuple(tuple) {
  var b = tuple[1];
  var a = tuple[0];
  if (a.TAG === /* Ok */0) {
    if (b.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: [
                a._0,
                b._0
              ]
            };
    } else {
      return {
              TAG: /* Error */1,
              _0: b._0
            };
    }
  } else {
    return {
            TAG: /* Error */1,
            _0: a._0
          };
  }
}

var ResultMonad = {
  liftTuple: liftTuple
};

exports.ResultMonad = ResultMonad;
/* No side effect */
