// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var TodoService = require("./TodoService.bs.js");
var TodoStateManager = require("./TodoStateManager.bs.js");
var TodoBrowserManager = require("./TodoBrowserManager.bs.js");

var TodoServiceInBrowser = TodoService.TodoService(TodoBrowserManager.TodoBrowserManager, TodoStateManager.TodoStateManager);

Curry._1(TodoServiceInBrowser.rerenderClearForm, TodoServiceInBrowser.applyForm);

Curry._1(TodoServiceInBrowser.rerenderResponsibles, TodoServiceInBrowser.changeTask);

exports.TodoServiceInBrowser = TodoServiceInBrowser;
/* TodoServiceInBrowser Not a pure module */
