// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TodoTask = require("./TodoTask.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function addTask(t, task) {
  if (Belt_Array.some(t.tasks, (function (tsk) {
            return tsk.id === task.id;
          }))) {
    return {
            id: t.id,
            name: t.name,
            tasks: Belt_Array.map(t.tasks, (function (tsk) {
                    if (tsk.id === task.id) {
                      return task;
                    } else {
                      return tsk;
                    }
                  }))
          };
  } else {
    return {
            id: t.id,
            name: t.name,
            tasks: Belt_Array.concat(t.tasks, [task])
          };
  }
}

function switchChekedTask(t, taskId) {
  if (Belt_Array.some(t.tasks, (function (tsk) {
            return tsk.id === taskId;
          }))) {
    return {
            TAG: /* Ok */0,
            _0: {
              id: t.id,
              name: t.name,
              tasks: Belt_Array.map(t.tasks, (function (tt) {
                      if (tt.id === taskId) {
                        return TodoTask.switchChecked(tt);
                      } else {
                        return tt;
                      }
                    }))
            }
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: "Can not find Task in Responsible by taskId"
          };
  }
}

exports.addTask = addTask;
exports.switchChekedTask = switchChekedTask;
/* TodoTask Not a pure module */
