// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Uuid = require("uuid");

function $$new(name) {
  return {
          id: Uuid.v4(),
          name: name,
          isReady: false
        };
}

function switchChecked(t) {
  return {
          id: t.id,
          name: t.name,
          isReady: !t.isReady
        };
}

exports.$$new = $$new;
exports.switchChecked = switchChecked;
/* uuid Not a pure module */
