// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var TodoTask = require("./TodoTask.bs.js");
var Js_string = require("rescript/lib/js/js_string.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var TodoResponsible = require("./TodoResponsible.bs.js");

function TodoService(TBM, TSM) {
  var rerenderClearForm = function (applyForm) {
    var errMsg = Curry._1(TBM.renderClearForm, undefined);
    if (errMsg.TAG === /* Ok */0) {
      var errMsg$1 = Curry._1(TBM.setFormOnApplyAction, applyForm);
      if (errMsg$1.TAG === /* Ok */0) {
        console.log("");
        return ;
      }
      console.log("Error:", errMsg$1._0);
      return ;
    }
    console.log("Error:", errMsg._0);
  };
  var collectTasks = function (acc, el) {
    return Belt_Array.concat(acc, el.tasks);
  };
  var rerenderResponsibles = function (changeTaskFun) {
    var state = Curry._1(TSM.readResponsiblesState, undefined);
    if (state.TAG === /* Ok */0) {
      var state$1 = state._0;
      var a = Curry._1(TBM.renderResponsibles, state$1);
      if (a.TAG === /* Ok */0) {
        var tasks = Belt_Array.reduce(state$1, [], collectTasks);
        var setTaskResults = Belt_Array.map(tasks, (function (t) {
                return Curry._2(TBM.setTaskOnClickAction, t.id, changeTaskFun);
              }));
        var errorMsgs = Belt_Array.map(setTaskResults, (function (tr) {
                if (tr.TAG === /* Ok */0) {
                  return "";
                } else {
                  return tr._0;
                }
              }));
        var errorMsg = Js_string.concatMany(errorMsgs, "");
        if (errorMsg.length > 0) {
          console.log("SetTaskErrors: ", errorMsg);
        } else {
          console.log("");
        }
        return ;
      }
      console.log("Error: ", a._0);
      return ;
    }
    console.log("Error: ", state._0);
  };
  var changeTask = function (taskId) {
    var errMsg = Curry._1(TSM.readResponsiblesState, undefined);
    if (errMsg.TAG !== /* Ok */0) {
      return {
              TAG: /* Error */1,
              _0: errMsg._0
            };
    }
    var newResps = Belt_Array.map(errMsg._0, (function (r) {
            var nr = TodoResponsible.switchChekedTask(r, taskId);
            if (nr.TAG === /* Ok */0) {
              return nr._0;
            } else {
              return r;
            }
          }));
    var errMsg$1 = Curry._1(TSM.writeResponsiblesState, newResps);
    if (errMsg$1.TAG !== /* Ok */0) {
      return {
              TAG: /* Error */1,
              _0: errMsg$1._0
            };
    }
    rerenderResponsibles(changeTask);
    return {
            TAG: /* Ok */0,
            _0: undefined
          };
  };
  var applyForm = function (param) {
    var errMsg = Curry._1(TBM.readFormVal, undefined);
    var setStateResult;
    if (errMsg.TAG === /* Ok */0) {
      var formVal = errMsg._0;
      var errMsg$1 = Curry._1(TSM.readResponsiblesState, undefined);
      setStateResult = errMsg$1.TAG === /* Ok */0 ? Curry._1(TSM.writeResponsiblesState, Belt_Array.map(errMsg$1._0, (function (r) {
                    return TodoResponsible.addTask(r, TodoTask.$$new(formVal));
                  }))) : ({
            TAG: /* Error */1,
            _0: errMsg$1._0
          });
    } else {
      setStateResult = {
        TAG: /* Error */1,
        _0: errMsg._0
      };
    }
    if (setStateResult.TAG !== /* Ok */0) {
      return {
              TAG: /* Error */1,
              _0: setStateResult._0
            };
    }
    rerenderClearForm(applyForm);
    return {
            TAG: /* Ok */0,
            _0: undefined
          };
  };
  var changeChecked = function (taskId) {
    var errMsg = Curry._1(TSM.readResponsiblesState, undefined);
    if (errMsg.TAG === /* Ok */0) {
      return Curry._1(TSM.writeResponsiblesState, Belt_Array.map(errMsg._0, (function (r) {
                        var rr = TodoResponsible.switchChekedTask(r, taskId);
                        if (rr.TAG === /* Ok */0) {
                          return rr._0;
                        } else {
                          return r;
                        }
                      })));
    } else {
      return {
              TAG: /* Error */1,
              _0: errMsg._0
            };
    }
  };
  return {
          rerenderClearForm: rerenderClearForm,
          collectTasks: collectTasks,
          rerenderResponsibles: rerenderResponsibles,
          changeTask: changeTask,
          applyForm: applyForm,
          changeChecked: changeChecked
        };
}

exports.TodoService = TodoService;
/* TodoTask Not a pure module */
