// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");

let globState = [
        {
            id: "cfddfeec-436c-413b-8ea4-dc3bbd40cd53",
            name: "Mary",
            tasks: [
                {
                    id: "5b72058d-d1f9-4192-8fbd-74b63549ec6f",
                    name: "Power up PC",
                    isReady: false,
                },
                {
                    id: "50acd125-4a6e-4af9-8fe1-2f5ae486c1c2",
                    name: "Groove the cat",
                    isReady: true,
                }
            ]
        }
    ]
;

function readResponsiblesState(param) {
  try {
    var result = globState;
    return {
            TAG: /* Ok */0,
            _0: result
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var msg = obj._1.message;
      return {
              TAG: /* Error */1,
              _0: msg !== undefined ? msg : ""
            };
    }
    throw obj;
  }
}

function writeResponsiblesState(newResps) {
  try {
    var result = (function(resps) {
                    console.log("New state: ", resps);
                    globState = resps;
                });
    return {
            TAG: /* Ok */0,
            _0: result(newResps)
          };
  }
  catch (raw_obj){
    var obj = Caml_js_exceptions.internalToOCamlException(raw_obj);
    if (obj.RE_EXN_ID === Js_exn.$$Error) {
      var msg = obj._1.message;
      return {
              TAG: /* Error */1,
              _0: msg !== undefined ? msg : ""
            };
    }
    throw obj;
  }
}

var TodoStateManager = {
  readResponsiblesState: readResponsiblesState,
  writeResponsiblesState: writeResponsiblesState
};

exports.TodoStateManager = TodoStateManager;
/*  Not a pure module */
