// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Uuid = require("uuid");

function $$new(name) {
  return {
          id: Uuid.v4(),
          name: name,
          isReady: false
        };
}

function switchChecked(t) {
  return {
          id: t.id,
          name: t.name,
          isReady: !t.isReady
        };
}

function refreshSame(old, $$new) {
  if ($$new.id === old.id) {
    return $$new;
  } else {
    return old;
  }
}

var TodoTask = {
  $$new: $$new,
  switchChecked: switchChecked,
  refreshSame: refreshSame
};

exports.TodoTask = TodoTask;
/* uuid Not a pure module */
