// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TodoTask = require("./TodoTask.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function withTasks(t, tasks) {
  return {
          id: t.id,
          name: t.name,
          tasks: tasks
        };
}

function addTask(t, task) {
  if (Belt_Array.some(t.tasks, (function (tsk) {
            return tsk.id === task.id;
          }))) {
    return withTasks(t, Belt_Array.map(t.tasks, (function (tsk) {
                      return TodoTask.TodoTask.refreshSame(tsk, task);
                    })));
  } else {
    return withTasks(t, Belt_Array.concat(t.tasks, [task]));
  }
}

function switchChekedTask(t, taskId) {
  if (Belt_Array.some(t.tasks, (function (tsk) {
            return tsk.id === taskId;
          }))) {
    return {
            TAG: /* Ok */0,
            _0: withTasks(t, Belt_Array.map(t.tasks, (function (tt) {
                        if (tt.id === taskId) {
                          return TodoTask.TodoTask.switchChecked(tt);
                        } else {
                          return tt;
                        }
                      })))
          };
  } else {
    return {
            TAG: /* Error */1,
            _0: "Can not find Task in Responsible by taskId"
          };
  }
}

function tryToSwitchChackedTask(t, taskId) {
  var r = switchChekedTask(t, taskId);
  if (r.TAG === /* Ok */0) {
    return r._0;
  } else {
    return t;
  }
}

var TodoResponsible = {
  withTasks: withTasks,
  addTask: addTask,
  switchChekedTask: switchChekedTask,
  tryToSwitchChackedTask: tryToSwitchChackedTask
};

exports.TodoResponsible = TodoResponsible;
/* TodoTask Not a pure module */
